zegami/zegami-python-sdk

requirements.txt, zegami_client.py
Fix concurrent.futures import
Fix some requirements
Allow to specify separator when fetching data file
=> Small fixes

examples/add_classification.py, examples/add_clustering.py, zegami_sdk/client.py, zegami_sdk/collection.py, zegami_sdk/nodes.py, zegami_sdk/util.py, zegami_sdk/workspace.py
* New module providing helper functions for working with nodes
* New example file for inserting some new nodes into a collection
We might want to iterate on the approach for this, perhaps having a node class analagous to the Collection and Workspace ones, but just having these helper functions is a useful step forward.
Some other slightly more general changes
* Add a put request capability
* Add repr functions for workspace and collection
* Use response.ok to check success, so that 204 codes also pass.
=> Add some functionality to modify the collection graph

README.md
This comes out as a broken image when we publish to pypi
=> Remove readme image - ZGM-7229

examples/add_mask_annotation.py
New node introduced in https://github.com/zegami/zegami-cloud/pull/1053
=> Add script to insert a maskrcnn annotation node

.flake8, examples/add_clustering.py, examples/add_mask_annotation.py, zegami_sdk/_annotation_methods.py, zegami_sdk/annotation.py, zegami_sdk/client.py, zegami_sdk/collection.py, zegami_sdk/nodes.py, zegami_sdk/source.py, zegami_sdk/stats.py, zegami_sdk/util.py, zegami_sdk/workspace.py
Add flake8 file and fixup linting
=> Add flake8 file and fixup linting

.vscode/launch.json, requirements.txt, zegami_sdk/client.py, zegami_sdk/util.py, zegami_sdk/workspace.py
- Added delete method for requests
- Added launch.json for running examples from the folder from vscode
- Added workspace storage, create, read and delete methods
=> Added workspace storage functions

examples/add_annotation_score.py
https://zegami.atlassian.net/browse/ZGM-7294
https://zegami.atlassian.net/browse/ZGM-7295
=> Script to insert a annotation score node

setup.py, zegami_sdk/collection.py
Fix for https://zegami.atlassian.net/browse/ZGM-7331
Also added recently introduced requirements to setup.py
=> Fix get v1 annotations

zegami_sdk/annotation.py
This updates the image encoding to match what's worked successfully in zegami-cloud, and what's easily rendered.
Still some changes needed to ensure data is uploaded in the right format, but that change can be made as a part of uploading legacy annotation data.
=> Encode masks as base64 1-bit pngs

examples/retrofit_image_clustering.py
Was used successfully on the CCRF collection, may not work on all collections.
=> Script to retrofit clustering to a collection

zegami_sdk/collection.py
- `self.tags` is dict with keys as tag names and values as an list of indicies.
- `get_rows_by_tags` receives a list of tag names and returns rows of metadata which has tags in the tag names.
- tags are cached by default
https://zegami.atlassian.net/browse/ZGM-7419
=> Add get_rows_by_tags

.vscode/settings.json, setup.py, zegami_sdk/client.py, zegami_sdk/collection.py, zegami_sdk/util.py
Added functionality for replacing collection data from the sdk
Added methods for creating and uploading to blob storage
[](https://zegami.atlassian.net/browse/ZGM-7215)
=> Replace data

.github/workflows/ci.yaml, Dockerfile, Makefile, docker-compose.yaml, requirements.txt, setup.py, zegami_sdk/collection.py, zegami_sdk/util.py
Build the sdk inside docker with the correct libraries installed, add linting and add both to Github workflows.
Also includes a manual workflow trigger
=> Build the wheels and set version via environment variable

zegami_sdk/collection.py
- Updated to not cache tags
- `delete_images_with_tag` should delete all the images in a collection with tag `delete`
https://zegami.atlassian.net/browse/ZGM-7479
=> Delete images in a collection with the tag 'delete'

zegami_sdk/client.py, zegami_sdk/collection.py
This also fixes some changes from the prior PR for uploading annotations (incorrectly).
=> Add annotation delete functionality

examples/create_collection.py, requirements.txt, setup.py, zegami_sdk/client.py, zegami_sdk/collection.py, zegami_sdk/source.py, zegami_sdk/util.py, zegami_sdk/workspace.py
Added image upload in the sources.py file in order to be used for both v1 and v2 collections
Added methods for assining images to smaller lists and uploading via threads
Changed image upload to support bulk upload
Changed how blob storage ids are fetching in order to support bulk upload
Added methods for creating empty and normal collections in workspace.py
=> Added collection creation functionality

zegami_sdk/source.py
This should work for both relative and absolute paths now
=> Fixed an issue with relative paths

zegami_sdk/_annotation_methods.py, zegami_sdk/collection.py
If no type provided, the default annotations returned will be mask annotations.
https://zegami.atlassian.net/browse/ZGM-7582
=> Update all annotation endpoints to be able to filter by type

zegami_sdk/collection.py, zegami_sdk/source.py, zegami_sdk/util.py
https://zegami.atlassian.net/browse/ZGM-7440
=> Update uploaded blob id to be imagetsetsORdatasets/<upload__id>/<uuid()>

.vscode/launch.json, examples/download_tagged_images.py, zegami_sdk/collection.py
Two new functions to save image to disk as well as an example of its use.
=> Add functionality to save images to disk

zegami_sdk/collection.py
Changed type to anno_type in v2 annotation functions
=> Changed type to anno_type in v2 annotation functions

zegami_sdk/collection.py
https://zegami.atlassian.net/browse/ZGM-7815
=> Fix get_annotations_for_image for v2 collection

examples/manipulate_userdata.py, zegami_sdk/collection.py
add functionality to set userdata with example. This is required for the omero bridge work
=> add functionality to set userdata

.vscode/launch.json, examples/create_collection.py, examples/create_empty_collection.py, setup.py, zegami_sdk/_annotation_methods.py, zegami_sdk/source.py
=> upload images in groups

setup.py, zegami_sdk/util.py
=> Blobstore should retry uploads to http blobstore

examples/add_images_to_collection.py, setup.py, zegami_sdk/collection.py
Mimics the creation interface, so does the same checks for values being present in the images column
=> Add new interface  to add images and data to a coll - ZGM-8015

examples/create_collection.py, zegami_sdk/source.py, zegami_sdk/util.py
- Added `UrlSource` class as a subclass of `UploadableSource`, and update the upload imageset to be transfer imageset
- Added example usage in `create_collections.py`
https://zegami.atlassian.net/browse/ZGM-8136
=> Create collection with url imageset

examples/add_custom_feature _extraction.py
Create examples to run a custom feature extraction model and output the results with clustering. 
Working on top of https://github.com/zegami/zegami-cloud/pull/1176
=> Create add_custom_feature _extraction.py

zegami_sdk/collection.py
A couple of instances missed this change
=> Change annotations kwarg from type to anno_type

zegami_sdk/collection.py
Works for collections with different types of annotations.
=> Get annotations metadata csv

zegami_sdk/source.py
This should replace the old e2e test to check for fetch job.
=> Use new fetch job to create url imageset collection

zegami_sdk/annotation.py
Enable creation of BB annotations from SDK
=> BB annotations class

zegami_sdk/annotation.py
Enables the creation of polygon annotations from SDK.
=> Add polygon class

examples/add_image_feature_pipeline.py, zegami_sdk/collection.py, zegami_sdk/nodes.py
- Interface to add feature pipeline and configure the mRMR node and clustering node params
- The sequence is, adding mRMR node, adding clustering node, adding mapping node, updating output node, adding snapshot if required.
- Make clustering columns names include `target_column` and `K` value
- One awkward thing is currently needing to specify the column order of clustering node
https://zegami.atlassian.net/browse/ZGM-8262
https://zegami.atlassian.net/browse/ZGM-8266
=> Add feature pipeline

examples/add_image_feature_pipeline.py, zegami_sdk/collection.py
- Returned `feature_pipelines` is a list of pipelines that are ready to be used for `add_feature_pipeline`
- Amended `parse_source` to accept source name
https://zegami.atlassian.net/browse/ZGM-8263
=> Add get_feature_pipelines

zegami_sdk/workspace.py
Small tweak to make it slightly easier to use
=> Return collection object when creating a collection

examples/add_image_feature_pipeline.py
Working on top of https://github.com/zegami/zegami-cloud/pull/1192
=> Update example add_image_feature_pipeline.py

zegami_sdk/collection.py
https://zegami.atlassian.net/browse/ZGM-8314
=> Fix mRMR snapshot not visible

README.md
We should follow up with some further changes:
* Move the Developer section to CONTRIBUTING.md
* Make reference to the examples
* Cover collection creation
* Cover collection updating
* Cover annotations
=> A few tweaks to make the readme a bit more accurate

examples/add_explainability_map.py, zegami_sdk/collection.py
https://zegami.atlassian.net/browse/ZGM-8321
=> Collection add_source and first pass of explainability map example

zegami_sdk/collection.py
Shouldn't mutate original data
=> FIx v1 collection source_name

.github/CODEOWNERS, zegami_sdk/collection.py
Also fix codeowners for this repo
=> Name is optional when duplicating a collection

examples/train_model_on_duplicated_collection.py, examples/upload_model_duplicate_collection.py, zegami_sdk/collection.py
- `upload_model_duplicate_collection.py` : upload model -> duplicate collection -> add explainability map and clustering to duplicated collection
- `train_model_on_duplicated_collection.py`: duplicate collection -> TODO: train model on duplicated collection -> upload model -> add explainability map and clustering to duplicated collection
=> Add example scripts for machine learning pipelines

zegami_sdk/source.py
Tested, limits the result of recursive search to os.path.basename(fp) existing within the provided list, if the list is provided with > 0 entries.
=> Added filename_filter to UploadableSource

zegami_sdk/collection.py
https://zegami.atlassian.net/browse/ZGM-8498
=> Improve docstrings for mrmr pipeline functions
